In [2]:
!pip install numpy

In [3]:
import numpy as np

# numpy 실습

In [4]:
# numpy 라이브러리 설치
# pip install numpy

In [14]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#array의 타입 확인.
type(arr)

numpy.ndarray

In [16]:
#array의 형태(크기)를 확인
arr.shape

(10,)

In [17]:
# 데이터 타입 확인
arr.dtype

dtype('int32')

# 1차원 배열 

In [23]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# 선언문 def처럼
#변수명. shape / _ () 메서드 mathode

# 배열의 벡터화 연산

In [35]:
# 백터화 연산
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
2*x
#스칼라와 백터의 연산값.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
# 백터끼리 연산

a = np.array([1,2,3])
b = np.array([10,20,30])

In [42]:
2*a+b
# 사칙연산 순서는 같다.

array([12, 24, 36])

In [43]:
b-a

array([ 9, 18, 27])

In [44]:
a**2

array([1, 4, 9], dtype=int32)

In [45]:
a == 2
#참,거짓을 판단할 수 잇다.

array([False,  True, False])

In [46]:
b >10

array([False,  True,  True])

In [47]:
(a==2)&(b>10)
# a에 있는 2의 값은 트루
# b에 있는 값이 10보다 클때
#and 함수라 둘다 충족하는 2번째 명만 true

array([False,  True, False])

# 2차원 배열

In [48]:
#다차원 배열 자료 구조
#2차원 배열은 행렬로 행과 열로 구성.

In [49]:
c = np.array([[0,1,2],
              [3,4,5]])

In [50]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
len(c)
# 두개의 값을 가지고 있다.

2

In [52]:
c.shape
#행의 크기가 2고, 배열이 3인 함수.

(2, 3)

# 3차원 배열 

In [ ]:
# 2.9 3차원 배열 생성 (2*3*4 array)

In [57]:
d = np.array([[[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
            [[11,12,13,14],
            [15,16,17,18],
            [19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [58]:
len(d)

2

In [59]:
len(d[0])

3

In [60]:
len(d[0][0])

4

In [61]:
# 배열의 차원과 크기

In [62]:
ab = np.array([1,2,3])

In [63]:
print(ab.ndim)
print(ab.shape)

1
(3,)


In [65]:
abc=np.array([[0,1,2],[3,4,5]])
abc

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
print(abc.ndim)
print(abc.shape)

2
(2, 3)


# 배열의 인덱싱 

In [67]:
# 1차원 배열의 인덱싱
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [68]:
a[2]
# 0,1,2 자리를 찾아서 3번째 자리의 숫자를 반환한다.

2

In [69]:
a[-1]
# -1 를 사용하여 '4' 을 추출.

4

### 다차원 배열의 인덱싱

In [70]:
# 배열 객체로  구현한 다차원 배열의 원소 중 하나의 개체를 선택
# 콤마로 구분된 차원을 축(axis)이라 하며, 그래프의 x,y축과 동일.

In [71]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [73]:
b[0,0]

0

In [74]:
b[0,1]

1

In [75]:
b[-1,-1]

5

### 불리언 인덱싱 

In [76]:
# 불리안 배열 인덱싱 방식은 인덱스 배열의 원소가 true, false 두 값으로만 구성
# 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 동일한 조건

In [89]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

idx = np.array([True,False,True,False,True,
            False,True,False,True,False])

a[idx]

array([0, 2, 4, 6, 8])

In [90]:
a%2
# 방법 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [91]:
a%2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [92]:
a[a%2 == 0]

array([0, 2, 4, 6, 8])

### 배열의 슬라이싱

In [93]:
# 배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 선택.
# 일반적인 파이선의 슬라이싱과 comma를 함께 사용

In [94]:
#sliicng
#[:] 배열 전체
#[0:n] 0에서  n 번째 까지
#[:5] 4번째 까지
#[2:]  2번째 부터 끝까지


In [96]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [98]:
a[0,:]
# 첫번째 행 전체

array([0, 1, 2, 3])

In [100]:
a[:,2]
# 두번째 열 전체.

array([2, 6])

In [101]:
a[:2,:2]
# 첫번째 행 2열, 두번째 행 2열

array([[0, 1],
       [4, 5]])

In [103]:
a[-1,:-1]

array([4, 5, 6])

### 데이터 타입

In [104]:
#ndarray클래스는 데이터가 같은 자료형
#array 명령으로 배열을 만들 때 자료형 지정은 dtype 사용

In [105]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [108]:
b = np.array([1.,2.,3])
b.dtype
# 실수

dtype('float64')

In [109]:
c = np.array([1,2,3.])
c.dtype
# 실수가 하나 있어서 실수로 결과나옴.

dtype('float64')

In [110]:
d = np.array([1,2,3], dtype="f")
d.dtype
# f로 지정하면 'float 32' 가 나온다.
# f8로 지정하면 'float64'가 나온다.

dtype('float32')

In [111]:
e = np.array([1,2,'ml'])
e

array(['1', '2', 'ml'], dtype='<U11')

In [112]:
e.dtype

dtype('<U11')

# 배열 생성 함수

In [113]:
#np.zeros
#'0'으로 초기화된 배열을 생성.

In [114]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [115]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
c = np.zeros((5,2),dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [118]:
# np.ones
# '1' 로 초기화된 배열을 생성.

In [119]:
d = np.ones((2,3,4),dtype='i8')
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

# np.arange

In [120]:
# 파이썬 어렌지와 동일.

In [121]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.arange(1,22,2)
# 시작값, 마지막값, 단계

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

### 전치연산

In [124]:
#배열의  전치
#행과 열을 바꾸는 전치연산으로 t 속성 사용

In [125]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열의 크기 변환

In [127]:
# 배열의 변형
#만들어진 배열의 내부 데이터는 보존한 채로 형태만 reshape 함수로 변형

In [128]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
b = a.reshape(3,4)
b
# 1차원 배열을 3*4 행렬로 변형.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

백터화 연산 

In [131]:
#x벡터와 y벡터의 연산시
#z = x + y

### 벡터화 연산

In [133]:
x = np.arange(1,10001)
y = np.arange(10001,20001)
x,y

(array([    1,     2,     3, ...,  9998,  9999, 10000]),
 array([10001, 10002, 10003, ..., 19998, 19999, 20000]))

In [134]:
x+y

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

### 벡터 연산  - 지수, 제곱, 로그함수

In [136]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [138]:
np.exp(a)
# 지수 함수

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [140]:
10**a
# 제곱

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [141]:
a**10

array([      0,       1,    1024,   59049, 1048576], dtype=int32)

In [143]:
np.log(a+1)
# 로그 함수

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### 스칼라와 벡터 연산 

In [145]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [149]:
x = np.arange(12).reshape(3,4)
x
# 12 까지 호출후 3 by 4 표.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드 캐스팅

In [151]:
# 벡터 연산 시에 두 벡터의 크기가 동일한 조건 요구
# 브로드캐스팅은 서로 닫른 크기를 가진 두 배열의 사칙 연산에서,
# 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춰준다.

In [156]:
x = np.array([[0,1,2],[1,2,3],[2,3,4],[4,5,6]])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [157]:
y = np.arange(3)
y

array([0, 1, 2])

In [158]:
x+y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [4, 6, 8]])

# 차원축소 연산 

In [159]:
# 1차원 배열의 차원축소 연산
# 차원 축소연산은 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 1차원 벡터가 반환
# numpy 메서드
# - min(최소) max(최대) argmin argmax - 자릿수
# - sum mean median std var
# - all any

In [160]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [161]:
np.sum(x)

10

In [162]:
x.sum()

10

In [172]:
x = np.array([333,2,8888,4])
x

array([ 333,    2, 8888,    4])

In [173]:
x.min()

2

In [174]:
x.max()

8888

In [177]:
x.argmin()
# 최소값의 위치.

1

In [178]:
x.argmax()
#최대값의 위치.

2

In [179]:
y = np.array([4,555,222222,9999])
y

array([     4,    555, 222222,   9999])

In [181]:
y.mean()
# 평균값 

58195.0

In [184]:
np.median(y)
# 배열 후 중간에 있는 중간값.

5277.0

### 2차원 배열의 차원축소 연산

In [186]:
#연산의 대상이 2차원 이상인 경우네는 어느 차원으로 계산을 할 지를 axis 인수를 사용
# axis=0 인 경우는 열 연산, axis=1인 경우는 행 연산
# 디폴트 값은 axis=0

In [187]:
x = np.array([[1,3],[2,4]])
x

array([[1, 3],
       [2, 4]])

In [189]:
x.sum()

10

In [191]:
x.sum(axis=0)
# 2차열 배열에서 더하고 나서 1차열 배열로 나열.

array([3, 7])

In [192]:
x.sum(axis=1)

array([4, 6])

### 통계함수

In [193]:
# 기술 통계
# count. sum. mean. (std, var), (min, max), (argmin,argmax), cumsum, cumprod

In [194]:
x = np.array([1,51,62,6234,2346,1,7,86,9,42,54,78,9,-2,])
x

array([   1,   51,   62, 6234, 2346,    1,    7,   86,    9,   42,   54,
         78,    9,   -2])

In [195]:
len(x)

14

In [197]:
np.mean(x)
# mean 평균값.

641.2857142857143

In [198]:
np.var(x) 
# 분산

2759559.3469387754

In [199]:
np.std(x)

1661.1921463030023

In [200]:
np.max(x)

6234

In [201]:
np.min(x)

-2

In [202]:
np.median(x)

46.5

In [203]:
np.count()
# 지원하지 않는 함수.

AttributeError: module 'numpy' has no attribute 'count'

### 난수생성

In [204]:
#데이터를 무작위로 섞거나 임의의 수 즉, 난수를 발생시키는 numpy의 random 서브패키지 사용 명령어

# rand : 0부터1사이의 균일 분포
# randn : 가우시안 표준 정규 분포
# randint : 균일 분포의 정수 난수


In [207]:
np.random.seed(0)
# 이 랜덤값은 0이라는 그룹이 생긴다.
# 0이외에 다른숫자를 넣어서 다시 해도 된다.
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [208]:
np.random.seed(1)
np.random.rand(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [209]:
np.random.rand(3,2)

array([[0.41919451, 0.6852195 ],
       [0.20445225, 0.87811744],
       [0.02738759, 0.67046751]])

### randint 명령

In [223]:
np.random.seed(4)
np.random.randint(10,21,size=10)

array([20, 17, 15, 11, 18, 17, 18, 12, 19, 20])

In [221]:
np.random.randint(10,20,size=(3,5))

array([[17, 11, 15, 17, 10],
       [11, 14, 16, 12, 19],
       [19, 19, 19, 11, 12]])